{{- if and (not .Values.global.externalSecrets.deploy) (.Values.global.createSlackWebhookSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook
stringData:
  slack_webhook: | 
    {{ .Values.global.slackWebhook | quote | b64enc }}
{{- end }}
