{{- if and (.Values.global.externalSecrets.deploy) (.Values.global.externalSecrets.createSlackWebhookSecret) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-webhook
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
  - secretKey: slack_webhook #pragma: allowlist secret
    remoteRef:
      #name of secret in secrets manager
      key: {{ .Values.global.externalSecrets.slackWebhookSecretName }}
{{- end }}
