apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.ssjDispatcher.ssjCreds.name }}
  namespace: {{.Values.ssjDispatcher.ssjCreds.namespace }}
spec:
  refreshInterval: {{ .Values.ssjDispatcher.ssjCreds.refreshInterval | default "2m" }}
  secretStoreRef:
    name: {{ .Values.ssjDispatcher.ssjCreds.secretStoreRefName }}
    kind: {{ .Values.ssjDispatcher.ssjCreds.secretStoreRefKind }}
  target:
    name: {{ .Values.ssjDispatcher.ssjCreds.targetName }}
  data:
    {{- toYaml .Values.ssjDispatcher.ssjCreds.data | nindent 6 }}
