{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dcf-dataservice-settings-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
  {{- if ne .Values.global.externalSecrets.googleCredsSecret  "" }}
    name: {{ .Values.global.externalSecrets.googleCredsSecret }}
    kind: ClusterSecretStore
  {{- else }}
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  {{- end  }}
  target:
    name: dcf-dataservice-settings-secrets
    creationPolicy: Owner
  data:
  - secretKey: binamb-gcloud-creds-secret
    remoteRef:
      property: binamb-gcloud-creds-secret
      #name of secret in secrets manager
      key: {{include "dcf-dataservice-settings-secrets" .}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dcf-dataservice-settings-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
  {{- if ne .Values.global.externalSecrets.googleCredsSecret  "" }}
    name: {{ .Values.global.externalSecrets.googleCredsSecret }}
    kind: ClusterSecretStore
  {{- else }}
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  {{- end  }}
  target:
    name: dcf-dataservice-settings-secrets
    creationPolicy: Owner
  data:
  - secretKey: binamb-dcf-dataservice-settings-secrets
    remoteRef:
      property: binamb-dcf-dataservice-settings-secrets
      #name of secret in secrets manager
      key: {{include "dcf-dataservice-settings-secrets" .}}
{{- end }}