{{- if .Values.global.externalSecrets.deploy }}
  {{ include "common.externalSecret.db" . }}

  apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    name: wts-g3auto
  spec:
    refreshInterval: 5m
    secretStoreRef:
      name: {{ include "common.SecretStore" . }}
      kind: SecretStore
    target:
      name: wts-g3auto
      creationPolicy: Owner
    data:
      - secretKey: appcreds.json
        remoteRef:
          key: {{ include "wts-g3auto" . }}

  {{- print "---" }}

  apiVersion: external-secrets.io/v1beta1
  kind: ExternalSecret
  metadata:
    name: wts-oidc-client
  spec:
    refreshInterval: 5m
    secretStoreRef:
      name: {{ include "common.SecretStore" . }}
      kind: SecretStore
    target:
      name: wts-oidc-client
      creationPolicy: Owner
    data:
      - secretKey: client_id
        remoteRef:
          key: {{ include "wts-oidc-client" . }}
      - secretKey: client_secret
        remoteRef:
          key: {{ include "wts-oidc-client" . }}
{{- end }}
