{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createK8sPelicanServiceSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: pelicanservice-g3auto
type: Opaque
{{- if .Values.global.aws.enabled }}
stringData:
  config.json: |-
{
  "manifest_bucket_name": "{{ .Values.pelican.bucket }}",
  "hostname": "{{ .Values.global.hostname }}",
  "aws_access_key_id": "{{ .Values.global.aws.pelican_user.access_key }}",
  "aws_secret_access_key": "{{ .Values.global.aws.pelican_user.access_secret }}"
}
{{- end }}
{{- end }}