apiVersion: v1
kind: ConfigMap
metadata:
  name: manifest-fence
data:
  fence-public-config.yaml: |
    {{- with .Values.FENCE_CONFIG }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
<<<<<<< HEAD
=======

>>>>>>> fix/fence_yaml_merge
