{{- if or (not .Values.global.externalSecrets.deploy) (and .Values.global.externalSecrets.deploy .Values.externalSecrets.createK8sFenceConfigSecret) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fence-config
data:
  fence-config.yaml: |
    BASE_URL: https://{{ .Values.global.hostname }}/user
    {{- with .Values.FENCE_CONFIG }}
    {{- toYaml . | nindent 4 }}
    {{ end }}
---
{{- end }}
