apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  {{- if .Values.global.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Values.global.aws.hatchery_role }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ssjdispatcher-role
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups:
      - ""
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nssjdispatcher-role-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ssjdispatcher.serviceAccountName" . }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssjdispatcher-role