apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  annotations:
<<<<<<< HEAD
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.global.aws.enabled }}
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Values.global.aws.hatchery_role }}
=======
    {{ with .Values.serviceAccount.annotations }}
    annotations:
      {{- toYaml . | nindent 4 }}
>>>>>>> master
    {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssjdispatcher-job-sa
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
<<<<<<< HEAD
=======
  annotations:
    {{- with .Values.jobServiceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
>>>>>>> master
