apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  {{- if .Values.global.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Values.global.aws.hatchery_role }}
  {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssjdispatcher-job-sa
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
