apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  {{- if .Values.global.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Values.global.aws.hatchery_role }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssjdispatcher-job-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.aws.account }}:role/{{ .Values.global.aws.hatchery_role }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ssjdispatcher-binding
subjects:
- kind: ServiceAccount
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io