apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ssjdispatcher.serviceAccountName" . }}
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  {{- if .Values.global.crossplane.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.crossplane.accountId }}:role/{{ .Values.global.environment }}-{{ .Release.Namespace }}-{{ include "ssjdispatcher.serviceAccountName" . }}
  {{- else }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssjdispatcher-job-sa
  labels:
    {{- include "ssjdispatcher.labels" . | nindent 4 }}
  {{- if and .Values.global.crossplane.enabled .Values.global.aws.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{{ .Values.global.crossplane.accountId }}:role/{{ .Values.global.environment }}-{{ include "ssjdispatcher.serviceAccountName" . }}
  {{- else }}
  {{- with .Values.jobServiceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
  {{- end }}

