{{ if .Values.global.externalSecrets.deploy }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ssjdispatcher-creds
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{include "common.SecretStore" .}}
    kind: SecretStore
  target:
    name: ssjdispatcher-creds
    creationPolicy: Owner
  data:
  - secretKey: credentials.json
    remoteRef: 
      key: {{ .Values.externalSecrets.serviceCreds }}
{{- else }}
apiVersion: v1
kind: Secret
metadata:
  name: ssjdispatcher-creds
type: Opaque
stringData:
  credentials.json: |-
    {
    "SQS": {
      "url": {{ .Values.ssjcreds.sqsUrl | quote }}
    },
    "JOBS": [
      {
        "name": {{ .Values.ssjcreds.jobName | quote }},
        "pattern": "{{ .Values.ssjcreds.jobPattern }}",
        "imageConfig": {
          "url": "{{ .Values.ssjcreds.jobUrl }}",
          "username": "{{ .Values.ssjcreds.jobUser }}",
          "password": "{{ .Values.ssjcreds.jobPassword }}",
          "metadataService": {
            "url": "{{ .Values.ssjcreds.metadataserviceUrl }}",
            "username": "{{ .Values.ssjcreds.metadataserviceUsername }}",
            "password": "{{ .Values.ssjcreds.metadataservicePassword }}"
          }
        },
        "RequestCPU": "{{ .Values.ssjcreds.jobRequestCpu }}",
        "RequestMem": "{{ .Values.ssjcreds.jobRequestMem }}"
      }
    ]
    }
{{- end }}